### ISSUE TITLE
yarn build fails Error: Could not find a compiler version matching ./node_modules/solc. compilers.solc.version option must be a string 

### ISSUE THREAD

**Issue by devrajsinghrawat** [energywebfoundation/origin#2360]
```
➜  origin git:(master) ✗ yarn build
yarn run v1.22.10
$ yarn build:static && yarn build:ts && lerna run build --scope @energyweb/origin-ui --stream
$ lerna run build:static --parallel
lerna notice cli v4.0.0
lerna info versioning independent
lerna info Executing command in 5 packages: "yarn run build:static"
@energyweb/exchange-ui-core: $ mkdir -p ./dist/styles/ && cp -r ./src/styles/*.scss ./dist/styles/
@energyweb/origin-ui-core: $ mkdir -p ./dist/styles/ && mkdir -p ./dist/assets/ && cp -r ./src/styles/*.scss ./dist/styles/ && cp -r ./assets/* ./dist/assets/
@energyweb/origin-ui-irec-core: $ mkdir -p ./dist/styles/ && mkdir -p ./dist/assets/ && cp -r ./src/styles/*.scss ./dist/styles/ && cp -r ./assets/* ./dist/assets/
@energyweb/exchange-token-account: $ yarn compile && yarn typechain:ethers
@energyweb/issuer: $ yarn compile && yarn typechain:registry && yarn typechain:issuer
@energyweb/issuer: $ truffle compile
@energyweb/exchange-token-account: $ truffle compile
@energyweb/issuer: Compiling your contracts...
@energyweb/issuer: ===========================
@energyweb/issuer: Error: Could not find a compiler version matching ./node_modules/solc. compilers.solc.version option must be a string specifying:
@energyweb/issuer:    - a path to a locally installed solcjs
@energyweb/issuer:    - a solc version or range (ex: '0.4.22' or '^0.5.0')
@energyweb/issuer:    - a docker image name (ex: 'stable')
@energyweb/issuer:    - 'native' to use natively installed solc
@energyweb/issuer:     at CompilerSupplier.badInputError (/Users/dev-d/1-WorkspaceSlockit/ew-nve/test/origin/node_modules/truffle/build/webpack:/packages/compile-solidity/compilerSupplier/index.js:33:1)
@energyweb/issuer:     at CompilerSupplier.load (/Users/dev-d/1-WorkspaceSlockit/ew-nve/test/origin/node_modules/truffle/build/webpack:/packages/compile-solidity/compilerSupplier/index.js:75:1)
@energyweb/issuer:     at loadParser (/Users/dev-d/1-WorkspaceSlockit/ew-nve/test/origin/node_modules/truffle/build/webpack:/packages/compile-solidity/profiler/loadParser.js:15:29)
@energyweb/issuer:     at Object.requiredSources (/Users/dev-d/1-WorkspaceSlockit/ew-nve/test/origin/node_modules/truffle/build/webpack:/packages/compile-solidity/profiler/index.js:19:1)
@energyweb/issuer:     at Object.sourcesWithDependencies (/Users/dev-d/1-WorkspaceSlockit/ew-nve/test/origin/node_modules/truffle/build/webpack:/packages/compile-solidity/index.js:68:45)
@energyweb/issuer:     at necessary (/Users/dev-d/1-WorkspaceSlockit/ew-nve/test/origin/node_modules/truffle/build/webpack:/packages/compile-solidity/index.js:42:1)
@energyweb/issuer:     at /Users/dev-d/1-WorkspaceSlockit/ew-nve/test/origin/node_modules/truffle/build/webpack:/packages/workflow-compile/index.js:38:1
@energyweb/issuer:     at async Promise.all (index 0)
@energyweb/issuer:     at compile (/Users/dev-d/1-WorkspaceSlockit/ew-nve/test/origin/node_modules/truffle/build/webpack:/packages/workflow-compile/index.js:28:1)
@energyweb/issuer:     at Object.compile (/Users/dev-d/1-WorkspaceSlockit/ew-nve/test/origin/node_modules/truffle/build/webpack:/packages/workflow-compile/index.js:71:47)
@energyweb/issuer:     at Object.run (/Users/dev-d/1-WorkspaceSlockit/ew-nve/test/origin/node_modules/truffle/build/webpack:/packages/core/lib/commands/compile.js:86:1)
@energyweb/issuer:     at Command.run (/Users/dev-d/1-WorkspaceSlockit/ew-nve/test/origin/node_modules/truffle/build/webpack:/packages/core/lib/command.js:140:1)
@energyweb/issuer: Truffle v5.3.3 (core: 5.3.3)
@energyweb/issuer: Node v14.16.1
@energyweb/issuer: error Command failed with exit code 1.
@energyweb/issuer: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
@energyweb/issuer: error Command failed with exit code 1.
@energyweb/issuer: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR! yarn run build:static exited 1 in '@energyweb/issuer'
lerna ERR! yarn run build:static stdout:
$ yarn compile && yarn typechain:registry && yarn typechain:issuer
$ truffle compile

Compiling your contracts...
===========================
Error: Could not find a compiler version matching ./node_modules/solc. compilers.solc.version option must be a string specifying:
   - a path to a locally installed solcjs
   - a solc version or range (ex: '0.4.22' or '^0.5.0')
   - a docker image name (ex: 'stable')
   - 'native' to use natively installed solc

    at CompilerSupplier.badInputError (/Users/dev-d/1-WorkspaceSlockit/ew-nve/test/origin/node_modules/truffle/build/webpack:/packages/compile-solidity/compilerSupplier/index.js:33:1)
    at CompilerSupplier.load (/Users/dev-d/1-WorkspaceSlockit/ew-nve/test/origin/node_modules/truffle/build/webpack:/packages/compile-solidity/compilerSupplier/index.js:75:1)
    at loadParser (/Users/dev-d/1-WorkspaceSlockit/ew-nve/test/origin/node_modules/truffle/build/webpack:/packages/compile-solidity/profiler/loadParser.js:15:29)
    at Object.requiredSources (/Users/dev-d/1-WorkspaceSlockit/ew-nve/test/origin/node_modules/truffle/build/webpack:/packages/compile-solidity/profiler/index.js:19:1)
    at Object.sourcesWithDependencies (/Users/dev-d/1-WorkspaceSlockit/ew-nve/test/origin/node_modules/truffle/build/webpack:/packages/compile-solidity/index.js:68:45)
    at necessary (/Users/dev-d/1-WorkspaceSlockit/ew-nve/test/origin/node_modules/truffle/build/webpack:/packages/compile-solidity/index.js:42:1)
    at /Users/dev-d/1-WorkspaceSlockit/ew-nve/test/origin/node_modules/truffle/build/webpack:/packages/workflow-compile/index.js:38:1
    at async Promise.all (index 0)
    at compile (/Users/dev-d/1-WorkspaceSlockit/ew-nve/test/origin/node_modules/truffle/build/webpack:/packages/workflow-compile/index.js:28:1)
    at Object.compile (/Users/dev-d/1-WorkspaceSlockit/ew-nve/test/origin/node_modules/truffle/build/webpack:/packages/workflow-compile/index.js:71:47)
    at Object.run (/Users/dev-d/1-WorkspaceSlockit/ew-nve/test/origin/node_modules/truffle/build/webpack:/packages/core/lib/commands/compile.js:86:1)
    at Command.run (/Users/dev-d/1-WorkspaceSlockit/ew-nve/test/origin/node_modules/truffle/build/webpack:/packages/core/lib/command.js:140:1)
Truffle v5.3.3 (core: 5.3.3)
Node v14.16.1
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR! yarn run build:static stderr:
error Command failed with exit code 1.
error Command failed with exit code 1.
lerna ERR! yarn run build:static exited 1 in '@energyweb/issuer'
lerna WARN complete Waiting for 1 child process to exit. CTRL-C to exit immediately.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by artursudnik** [comment]
Please give us more context. Did you go through the steps described in the Readme.md of this project? Rush has been introduced recently and should be used to set up and build the code.

**Comment by josipbagaric** [comment]
Yes, please use `rush build` instead of `yarn build`.

**Comment by devrajsinghrawat** [comment]
rush build works well
