### ISSUE TITLE
Is "bulk claim" feature already worked ?

### ISSUE THREAD

**Issue by andrii482** [energywebfoundation/origin#2670]
I try to claim few certificates, but get everytime errors:

### a)
If I try to claim certificate from "exchange" state - I get just `500 error`
https://github.com/energywebfoundation/origin/pull/2037
https://github.com/energywebfoundation/origin/pull/2518
![image](https://user-images.githubusercontent.com/61418776/126549005-feb6ae97-d059-44d0-b76d-059d8001974f.png)

### b) 
If try to claim certificate from "blockchain" state - I get error `Requested claiming of certificates, but you do not own certificates with ...`   

### b.1)
But when I disable this check in:
`packages/traceability/issuer-api/src/pods/certificate/handlers/batch-claim-certificates.handler.ts`
in line 43 I just make `if (false) {`

https://github.com/energywebfoundation/origin/blob/240cfed32efa8874d97cb6384f3a681909f3af0e/packages/traceability/issuer-api/src/pods/certificate/handlers/batch-claim-certificates.handler.ts#L43

It's make possible to make bulk claim in **b.1.1)** , but I still get error in **b.1.2)**

### b.1.1)
I add to `metamask` and to `User blockchain address`  account from .env (that is `EXCHANGE_WALLET_PUB`) and it's make possible to claim 2 certificates from "blockchain" state 
https://volta-explorer.energyweb.org/tx/0x0f9996d75600c3e4626b6ffa1d3eaf4b63f44d76ec50a864900f9db6be45c6d9/logs
Also (with same ^ settings) I can do bulk claim to certificates that are in "exchange" state
https://volta-explorer.energyweb.org/tx/0x8a60ee45ab9335173d7d203c6604f235500e84465cff69245f9cb1a67734b836/logs

### b.1.2) 
I add to metamask account that is pre-defined for `Device manager` in `User blockchain address` (`0x5B1B89A48C1fB9b6ef7Fb77C453F2aAF4b156d45`) and try to claim  few certificates that are in "blockchain" state, but get this error: 
![image](https://user-images.githubusercontent.com/61418776/126550723-5808b260-ac7f-4f3a-bd82-66daa20992ab.png)
<details>
  <summary>some clickable spoiler here:</summary>
<b>

```
{"statusCode":500,"message":"{\"reason\":\"cannot estimate gas; transaction may fail or may require manual gas limit\",\"code\":\"UNPREDICTABLE_GAS_LIMIT\",\"error\":{\"reason\":\"failed to meet quorum\",\"code\":\"SERVER_ERROR\",\"method\":\"estimateGas\",\"params\":{\"transaction\":{\"from\":\"0xF1F6619B38A98d6De0800F1DefC0a6399eB6d30C\",\"gasPrice\":{\"type\":\"BigNumber\",\"hex\":\"0x3c\"},\"to\":\"0x41Dcd1Ae7ea4bf591169313edb99dF349F91aca3\",\"data\":\"0x760c6caf0000000000000000000000005b1b89a48c1fb9b6ef7fb77c453f2aaf4b156d450000000000000000000000005b1b89a48c1fb9b6ef7fb77c453f2aaf4b156d4500000000000000000000000000000000000000000000000000000000000000c00000000000000000000000000000000000000000000000000000000000000120000000000000000000000000000000000000000000000000000000000000018000000000000000000000000000000000000000000000000000000000000001c00000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000a0000000000000000000000000000000000000000000000000000000000000009000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000f424000000000000000000000000000000000000000000000000000000000000f42400000000000000000000000000000000000000000000000000000000000000020e17e70474d988b017aaa3a5c9377c87a13cc4e5c118f3db6d8f9064192c2be8a000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000000280000000000000000000000000000000000000000000000000000000000000022000000000000000000000000000000000000000000000000000000000000000c000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000140000000000000000000000000000000000000000000000000000000000000018000000000000000000000000000000000000000000000000000000000000001c00000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000001b446576696365204d616e61676572204f7267616e697a6174696f6e00000000000000000000000000000000000000000000000000000000000000000000000011416464726573732c205a697020636f6465000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000247420000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000018323032312d30372d32315431383a31323a34302e3431375a00000000000000000000000000000000000000000000000000000000000000000000000000000018323032312d30372d32315431383a31323a34302e3431375a00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000022000000000000000000000000000000000000000000000000000000000000000c000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000140000000000000000000000000000000000000000000000000000000000000018000000000000000000000000000000000000000000000000000000000000001c00000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000001b446576696365204d616e61676572204f7267616e697a6174696f6e00000000000000000000000000000000000000000000000000000000000000000000000011416464726573732c205a697020636f6465000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000247420000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000018323032312d30372d32315431383a31323a34302e3431375a00000000000000000000000000000000000000000000000000000000000000000000000000000018323032312d30372d32315431383a31323a34302e3431375a00000000000000000000000000000000000000000000000000000000000000000000000000000000\",\"accessList\":null}},\"results\":[{\"weight\":1,\"start\":1626891177786,\"error\":{\"reason\":\"processing response error\",\"code\":\"SERVER_ERROR\",\"body\":\"{\\\"jsonrpc\\\":\\\"2.0\\\",\\\"error\\\":{\\\"code\\\":-32016,\\\"message\\\":\\\"The execution failed due to an exception.\\\",\\\"data\\\":\\\"Reverted\\\"},\\\"id\\\":102}\\n\",\"error\":{\"code\":-32016,\"data\":\"Reverted\"},\"requestBody\":\"{\\\"method\\\":\\\"eth_estimateGas\\\",\\\"params\\\":[{\\\"gasPrice\\\":\\\"0x3c\\\",\\\"from\\\":\\\"0xf1f6619b38a98d6de0800f1defc0a6399eb6d30c\\\",\\\"to\\\":\\\"0x41dcd1ae7ea4bf591169313edb99df349f91aca3\\\",\\\"data\\\":\\\"0x760c6caf0000000000000000000000005b1b89a48c1fb9b6ef7fb77c453f2aaf4b156d450000000000000000000000005b1b89a48c1fb9b6ef7fb77c453f2aaf4b156d4500000000000000000000000000000000000000000000000000000000000000c00000000000000000000000000000000000000000000000000000000000000120000000000000000000000000000000000000000000000000000000000000018000000000000000000000000000000000000000000000000000000000000001c00000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000a0000000000000000000000000000000000000000000000000000000000000009000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000f424000000000000000000000000000000000000000000000000000000000000f42400000000000000000000000000000000000000000000000000000000000000020e17e70474d988b017aaa3a5c9377c87a13cc4e5c118f3db6d8f9064192c2be8a000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000000280000000000000000000000000000000000000000000000000000000000000022000000000000000000000000000000000000000000000000000000000000000c000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000140000000000000000000000000000000000000000000000000000000000000018000000000000000000000000000000000000000000000000000000000000001c00000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000001b446576696365204d616e61676572204f7267616e697a6174696f6e00000000000000000000000000000000000000000000000000000000000000000000000011416464726573732c205a697020636f6465000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000247420000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000018323032312d30372d32315431383a31323a34302e3431375a00000000000000000000000000000000000000000000000000000000000000000000000000000018323032312d30372d32315431383a31323a34302e3431375a00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000022000000000000000000000000000000000000000000000000000000000000000c000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000140000000000000000000000000000000000000000000000000000000000000018000000000000000000000000000000000000000000000000000000000000001c00000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000001b446576696365204d616e61676572204f7267616e697a6174696f6e00000000000000000000000000000000000000000000000000000000000000000000000011416464726573732c205a697020636f6465000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000247420000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000018323032312d30372d32315431383a31323a34302e3431375a00000000000000000000000000000000000000000000000000000000000000000000000000000018323032312d30372d32315431383a31323a34302e3431375a00000000000000000000000000000000000000000000000000000000000000000000000000000000\\\"}],\\\"id\\\":102,\\\"jsonrpc\\\":\\\"2.0\\\"}\",\"requestMethod\":\"POST\",\"url\":\"http://91.229.216.226:8545\"}}],\"provider\":{\"_isProvider\":true,\"_events\":[],\"_emitted\":{\"block\":-2},\"formatter\":{\"formats\":{\"transaction\":{},\"transactionRequest\":{},\"receiptLog\":{},\"receipt\":{},\"block\":{},\"blockWithTransactions\":{},\"filter\":{},\"filterLog\":{}}},\"anyNetwork\":false,\"_networkPromise\":{},\"_maxInternalBlockNumber\":12694938,\"_lastBlockNumber\":-2,\"_pollingInterval\":4000,\"_fastQueryDate\":1626891173133,\"providerConfigs\":[{\"provider\":{\"_isProvider\":true,\"_events\":[],\"_emitted\":{\"block\":-2},\"formatter\":{\"formats\":{\"transaction\":{},\"transactionRequest\":{},\"receiptLog\":{},\"receipt\":{},\"block\":{},\"blockWithTransactions\":{},\"filter\":{},\"filterLog\":{}}},\"anyNetwork\":false,\"_networkPromise\":{},\"_maxInternalBlockNumber\":12694938,\"_lastBlockNumber\":-2,\"_pollingInterval\":4000,\"_fastQueryDate\":1626891176441,\"connection\":{\"url\":\"http://91.229.216.226:8545\"},\"_nextId\":103,\"_eventLoopCache\":{\"detectNetwork\":null,\"eth_chainId\":null,\"eth_blockNumber\":null},\"_network\":{\"chainId\":73799,\"name\":\"unknown\"},\"_internalBlockNumber\":{},\"_fastBlockNumber\":12694938,\"_fastBlockNumberPromise\":{}},\"weight\":1,\"stallTimeout\":750,\"priority\":1}],\"quorum\":0.5,\"_highestBlockNumber\":12694938,\"_network\":{\"chainId\":73799,\"name\":\"unknown\"},\"_internalBlockNumber\":{},\"_fastBlockNumber\":12694938,\"_fastBlockNumberPromise\":{}}},\"tx\":{\"data\":\"0x760c6caf0000000000000000000000005b1b89a48c1fb9b6ef7fb77c453f2aaf4b156d450000000000000000000000005b1b89a48c1fb9b6ef7fb77c453f2aaf4b156d4500000000000000000000000000000000000000000000000000000000000000c00000000000000000000000000000000000000000000000000000000000000120000000000000000000000000000000000000000000000000000000000000018000000000000000000000000000000000000000000000000000000000000001c00000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000a0000000000000000000000000000000000000000000000000000000000000009000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000f424000000000000000000000000000000000000000000000000000000000000f42400000000000000000000000000000000000000000000000000000000000000020e17e70474d988b017aaa3a5c9377c87a13cc4e5c118f3db6d8f9064192c2be8a000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000000280000000000000000000000000000000000000000000000000000000000000022000000000000000000000000000000000000000000000000000000000000000c000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000140000000000000000000000000000000000000000000000000000000000000018000000000000000000000000000000000000000000000000000000000000001c00000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000001b446576696365204d616e61676572204f7267616e697a6174696f6e00000000000000000000000000000000000000000000000000000000000000000000000011416464726573732c205a697020636f6465000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000247420000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000018323032312d30372d32315431383a31323a34302e3431375a00000000000000000000000000000000000000000000000000000000000000000000000000000018323032312d30372d32315431383a31323a34302e3431375a00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000022000000000000000000000000000000000000000000000000000000000000000c000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000140000000000000000000000000000000000000000000000000000000000000018000000000000000000000000000000000000000000000000000000000000001c00000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000001b446576696365204d616e61676572204f7267616e697a6174696f6e00000000000000000000000000000000000000000000000000000000000000000000000011416464726573732c205a697020636f6465000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000247420000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000018323032312d30372d32315431383a31323a34302e3431375a00000000000000000000000000000000000000000000000000000000000000000000000000000018323032312d30372d32315431383a31323a34302e3431375a00000000000000000000000000000000000000000000000000000000000000000000000000000000\",\"to\":{},\"from\":\"0xF1F6619B38A98d6De0800F1DefC0a6399eB6d30C\",\"gasPrice\":{},\"nonce\":{},\"gasLimit\":{},\"chainId\":{}}}"}
```
</details>

**Comment by josipbagaric** [comment]
Thanks for reporting @andrii482, will take a deeper look soon, but off the top of my head:

1. Are you using the latest `master` (i.e. development) branch?
2. Are you deploying to the Volta testnet or local ganache-cli instance?
2. Regarding the UNPREDICTABLE_GAS_LIMIT error, this was possibly caused by an automatic update of the `ethers` library to v5.4.x on the master branch. I've reverted the ethers version to 5.3.x in the meantime in [this PR](https://github.com/energywebfoundation/origin/pull/2654) so pulling the latest master should fix these errors appearing on the Volta testnet.

**Comment by andrii482** [comment]
### 1. 
Yep. I use master branch and last commit is from `Wed Jul 21 13:09:29 2021`

<details>
  <summary><code>git log && git branch</code> spoiler </summary>
$ git log

commit 240cfed32efa8874d97cb6384f3a681909f3af0e (HEAD -> master, origin/master, origin/HEAD)
Merge: 35740d5ec 5ab448adc
Author: Joseph Bagaric <bagaricjos@gmail.com>
Date:   Wed Jul 21 13:09:29 2021 +0200

    Merge pull request #2668 from energywebfoundation/feat/irec-device-types
    
    chore: update device types to I-REC definition
<br>
</details>



### 2. 

I use Volta testnet 
<details>
  <summary>details</summary>
and as you see in first topic  I provide you links to yours  block-explorer with my transactions 

https://volta-explorer.energyweb.org/tx/0x0f9996d75600c3e4626b6ffa1d3eaf4b63f44d76ec50a864900f9db6be45c6d9/logs

https://volta-explorer.energyweb.org/tx/0x8a60ee45ab9335173d7d203c6604f235500e84465cff69245f9cb1a67734b836/logs

</details>



### 3.
I already use your's https://github.com/energywebfoundation/origin/pull/2654 RP in my tests 
(actually, I'm on commit that is after your PR  that mentioned (6 commits after)) 


My mention is that the reason why I faced with error **b.1.2)**  is because I don't sign transaction via private_key/metamask (metamask window don't appear in both cases: in **b.1.2)** and **b.1.1)**. 
But in case **b.1.1)** private key stored in `.env`, so theoretically it can be used to sign transaction (without asking confirmation in metamask))

**Comment by andrii482** [comment]
Also, I have some question about `claim's` on `master` and `release` branch :  
### a)
 when we make `claim` on 'release'  branch - I see that last transfer is to owner wallet (but not in to 0x00...0000000 address like in "b)" case)  and in claim transaction details I don't see step, where sending tokens to '0x00...00000' address  happens
<details>
  <summary>Spoiler</summary>

![image](https://user-images.githubusercontent.com/61418776/126633478-15439572-a69b-4bda-ae9f-9b04fc885dd4.png)

![image](https://user-images.githubusercontent.com/61418776/126633589-b953f98e-40f9-48a8-8493-b364781345ff.png)

https://volta-explorer.energyweb.org/tx/0xb610b83e5c37cb6e868ca12e162899006096e9861653d0cea094ee61b99edb59/logs

</details>

### b)

 but if I make `claim` on `master` branch - looks like that now is like "tokens burning" (by sending them to 0x00...000000 address)

<details>
  <summary>spoiler</summary>

![image](https://user-images.githubusercontent.com/61418776/126633022-b1523d00-259f-42b6-9f19-6d5af7c2017d.png)

![image](https://user-images.githubusercontent.com/61418776/126633083-962e6468-6d49-42a1-8378-c3cd136855b0.png)

https://volta-explorer.energyweb.org/tx/0x4dc9406c4b5008342d5b68ae70da666813442fa4356190b5e42b085fb47395e5/logs
</details>

**Comment by andrii482** [comment]
Also, sometimes, I faced with this issue when try 'bulk claim'

```
[backend] @energyweb/origin-backend-app: [Nest] 14885   - 07/26/2021, 2:58:42 PM   [HTTPLoggingInterceptor] 200 | [PUT] /api/certificate-batch/claim - "invalid BigNumber value (argument=\"value\", value=undefined, code=INVALID_ARGUMENT, version=bignumber/5.3.0)" - 9ms +5730ms                                                                                                                                                                                                                                                                          
[backend] @energyweb/origin-backend-app: [Nest] 14885   - 07/26/2021, 2:58:42 PM   [ExceptionsHandler] invalid BigNumber value (argument="value", value=undefined, code=INVALID_ARGUMENT, version=bignumber/5.3.0) +2ms
[backend] @energyweb/origin-backend-app: Error: invalid BigNumber value (argument="value", value=undefined, code=INVALID_ARGUMENT, version=bignumber/5.3.0)
[backend] @energyweb/origin-backend-app:     at Logger.makeError (/home/user1/origin/common/temp/node_modules/.pnpm/@ethersproject/logger@5.3.0/node_modules/@ethersproject/logger/lib/index.js:187:21)
[backend] @energyweb/origin-backend-app:     at Logger.throwError (/home/user1/origin/common/temp/node_modules/.pnpm/@ethersproject/logger@5.3.0/node_modules/@ethersproject/logger/lib/index.js:196:20)
[backend] @energyweb/origin-backend-app:     at Logger.throwArgumentError (/home/user1/origin/common/temp/node_modules/.pnpm/@ethersproject/logger@5.3.0/node_modules/@ethersproject/logger/lib/index.js:199:21)
[backend] @energyweb/origin-backend-app:     at Function.BigNumber.from (/home/user1/origin/common/temp/node_modules/.pnpm/@ethersproject/bignumber@5.3.0/node_modules/@ethersproject/bignumber/lib/bignumber.js:241:23)
[backend] @energyweb/origin-backend-app:     at /home/user1/origin/packages/traceability/issuer-api/dist/js/src/pods/certificate/handlers/batch-claim-certificates.handler.js:42:77
[backend] @energyweb/origin-backend-app:     at Array.map (<anonymous>)
[backend] @energyweb/origin-backend-app:     at BatchClaimCertificatesHandler.execute (/home/user1/origin/packages/traceability/issuer-api/dist/js/src/pods/certificate/handlers/batch-claim-certificates.handler.js:42:44)
[backend] @energyweb/origin-backend-app:     at runMicrotasks (<anonymous>)
[backend] @energyweb/origin-backend-app:     at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

**Comment by josipbagaric** [comment]
> Also, I have some question about `claim's` on `master` and `release` branch :
> 
> ### a)
> when we make `claim` on 'release' branch - I see that last transfer is to owner wallet (but not in to 0x00...0000000 address like in "b)" case) and in claim transaction details I don't see step, where sending tokens to '0x00...00000' address happens
> 
> Spoiler
> ### b)
> but if I make `claim` on `master` branch - looks like that now is like "tokens burning" (by sending them to 0x00...000000 address)
> 
> spoiler

This happens because we changed the underlying ERC-1155 smart contracts.

The new ones are from OpenZeppelin and they have a different burning implementation, that emit this event.

**Comment by andrii482** [comment]
Thanks for your answer. We still  don't use `master` branch in main testing  now. So for now - I close this issue and stop my tests with `master` branch. Thanks 

> * Are you using the latest `master` (i.e. development) branch?
