### ISSUE TITLE
Rush update issue 

### ISSUE THREAD

**Issue by brahimbensalah** [energywebfoundation/origin#3342]
Hello i am trying use energy web origin but I come up with the showed in the image. I was wondering if anybody else encounter this issues and resolved it. 
I have been using the following to setup energy web origin https://github.com/energywebfoundation/origin. I get the following issue:

make : on entre dans le répertoire « /home/brahim/Bureau/origin/origin/commo
│   ACTION deps_sqlite3_gyp_action_before_build_target_unpack_sqlite_dep Relea
│ /bin/sh: 1: python: not found
│ make: *** [deps/action_before_build.target.mk:13 : Release/obj/gen/sqlite-au
│ make : on quitte le répertoire « /home/brahim/Bureau/origin/origin/common/te
│ gyp ERR! build error 
│ gyp ERR! stack Error: `make` failed with exit code: 2
│ gyp ERR! stack     at ChildProcess.onExit (/home/brahim/.rush/node-v14.19.0/
│ gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
│ gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_pr
│ gyp ERR! System Linux 5.13.0-30-generic
│ gyp ERR! command "/home/brahim/.nvm/versions/node/v14.19.0/bin/node" "/home/
│ gyp ERR! cwd /home/brahim/Bureau/origin/origin/common/temp/node_modules/.pnp
│ gyp ERR! node -v v14.19.0
│ gyp ERR! node-gyp -v v7.1.2
│ gyp ERR! not ok 
│ node-pre-gyp ERR! build error 
│ node-pre-gyp ERR! stack Error: Failed to execute '/home/brahim/.nvm/versions
│ node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/brahim/Bureau
│ node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
│ node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1058:16
│ node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal
│ node-pre-gyp ERR! System Linux 5.13.0-30-generic
│ node-pre-gyp ERR! command "/home/brahim/.nvm/versions/node/v14.19.0/bin/node
│ node-pre-gyp ERR! cwd /home/brahim/Bureau/origin/origin/common/temp/node_mod
│ node-pre-gyp ERR! node -v v14.19.0
│ node-pre-gyp ERR! node-pre-gyp -v v0.11.0
│ node-pre-gyp ERR! not ok 
│ Failed to execute '/home/brahim/.nvm/versions/node/v14.19.0/bin/node /home/b
└─ Failed in 4.6s
node_modules/.pnpm/tiny-secp256k1@1.1.6/node_modules/tiny-secp256k1: Running install script...
node_modules/.pnpm/ursa-optional@0.10.2/node_modules/ursa-optional: Running install script...
node_modules/.pnpm/utf-8-validate@5.0.7/node_modules/utf-8-validate: Running install script, done in 149ms
node_modules/.pnpm/web3-bzz@1.5.3/node_modules/web3-bzz: Running postinstall script, done in 42ms
node_modules/.pnpm/web3-bzz@1.6.1/node_modules/web3-bzz: Running postinstall script, done in 41ms
node_modules/.pnpm/github.com/web3-js/WebSocket-Node@ef5ea2f41daf4a2113b80c9223df884b4d56c400/node_modules/websocket: Running install script, done in 4.1s
node_modules/.pnpm/github.com/web3-js/scrypt-shim@aafdadda13e660e25e1c525d1f5b2443f5eb1ebb/node_modules/@web3-js/scrypt-shim: Running postinstall script, done in 455ms
 ERROR  Command failed with exit code 1.

The command failed:
 /home/brahim/Bureau/origin/origin/common/temp/pnpm-local/node_modules/.bin/pnpm install --store /home/brahim/Bureau/origin/origin/common/temp/pnpm-store --no-prefer-frozen-lockfile
ERROR: Error: The command failed with exit code 1

Giving up after 3 attempts

Deleting the "pnpm-store" folder

ERROR: The command failed with exit code 1

**Comment by maciejbrasewicz** [comment]
`sudo update-alternatives --install /usr/bin/python python /usr/bin/python3 1`

this should help

**Comment by firasbelhiba** [comment]
Try this : sudo update-alternatives --install /usr/bin/python python /usr/bin/python3 1

**Comment by parsanoori** [comment]
What's the equivalent of `update-alternatives` on other OSes for this purpose?
